export const FETCH_NEWS_START = 'FETCH_NEWS_START';
export const FETCH_NEWS_FINISH = 'FETCH_NEWS_FINISH';
export const FETCH_NEWS_ERROR = 'FETCH_NEWS_ERROR';
export const UPDATE_NEWS_DATA = 'UPDATE_NEWS_DATA';
export const CLEAR_NEWS_DATA = 'CLEAR_NEWS_DATA';
export const UPDATE_PAGINATION = 'UPDATE_PAGINATION';
export const UPDATE_SEARCH_KEYWORD = 'UPDATE_SEARCH_KEYWORD';
export const UPDATE_TOTAL_PAGE = 'UPDATE_TOTAL_PAGE';
